---
 - name: Smokefree Production  database dump
   hosts: nciws-p652-v
   become: yes
   become_user: root
   become_method: dzdo 
   vars:
     - sfgroot: /local/drupal/smokefree/sites/smokefree.gov
     - prodsqldump: /admfs/drupal-bkups/nciws-p652-v
     - prodtables: actiondeck,field_data_field_springboard_action_cards,field_revision_field_springboard_action_cards,webform_submissions,webform_submitted_data,users,users_roles,authmap
     - prodfile:  exportdb-eight.sql

   tasks:
     - name: Take sql dump of production file.
       shell: 
         cmd: "drush sql-dump --tables-list={{ prodtables }} > {{ prodsqldump }}/exportdb-eight.sql"
         chdir: "{{ sfgroot }}"


 









   

     
