---
 - name: "{{ site }} Production  database dump "
   hosts: nciws-p864-v
   become: yes
   become_user: drupal
   become_method: dzdo 
   vars:
     - site: springboard
     - siteroot: /local/drupal/{{ site }}/sites/{{ site }}
     - dblocation: /admfs/drupal_deployment/{{ site }}
     - prodsqlfile:  "{{ site }}-prod-db.sql"
     - drupalroot: /local/drupal/{{ site }}

   tasks:
     - name: Take sql dump of {{ site }}production.
       shell: 
         cmd: drush sql-dump --result-file={{ dblocation }}/{{ prodsqlfile }}
         chdir: "{{ siteroot }}"

#     - name: Take copy of production files systems
#       shell: 
#         cmd: tar -cf {{ proddump }}/{{ prodsite }} --exclude=sites/smokefree/settings.php sites
#         chdir: "{{ drupalroot }}"


 









   

     
