---
- name: Transfer db files
  hosts: '{{ host }}'
  become: yes
  become_user: root
  become_method: dzdo
  gather_facts: no
  vars:
    database_location: /admfs/drupal_deployment
    file_upload: '{{ file_upload }}'
    sitename: '{{ sitename }}'
    host: '{{ host }}'
  tasks:
    - name: copy file to admfs
      copy: src={{ item.src }} dest={{ item.dest }}
      with_items:
         - { src: '{{ upload }}/{{ file_upload }}', dest: '{{ database_location }}/{{ sitename }}/{{ sitename }}-database-update.sql' }
         
         

      
